version: "3"

services: 

  system-bd: 
    image: postgres:9.6
    volumes:
      - "./postgres-container/pgdata:/var/lib/postgresql/data/pgdata"
    ports: 
      - "54321:5432"
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
      POSTGRES_DB: larave_db
      PGDATA: /var/lib/postgresql/data/pgdata

    networks:
      - local

volumes:
  Service-Database:

networks: 
  local: 
    driver: bridge